spring:
  datasource:
    url: jdbc:mysql://localhost:3306/room_fit?rewriteBatchedStatements=true
#    url: jdbc:mysql://localhost:3306/room_fit?rewriteBatchedStatements=true&&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 24      # 최대 커넥션 수 (기본값: 10)
      minimum-idle: 10            # 최소 유휴 커넥션 수
      idle-timeout: 30000        # 유휴 커넥션 유지 시간 (밀리초)
      max-lifetime: 1800000      # 커넥션 최대 유지 시간 (밀리초)
      connection-timeout: 30000  # 커넥션 대기 시간 (밀리초)
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        order_updates: true
        order_inserts: true

    database-platform: org.hibernate.dialect.MySQLDialect

  threads:
    virtual:
      enabled: true

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.springframework.jdbc: DEBUG
