spring:
  datasource:
    url: jdbc:mysql://localhost:3306/room_fit?rewriteBatchedStatements=true&&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_updates: true
        order_inserts: true


    database-platform: org.hibernate.dialect.MySQLDialect

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.springframework.jdbc: DEBUG
