name: Build and Push Docker Image

on:
  push:
    branches:
      - test/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Docker 로그인
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. `application.yml` 파일 복원
      - name: Restore application.yml
        run: |
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_LOCAL_YML }}" | base64 --decode > src/main/resources/application-local.yml
          ls -l src/main/resources/

      # 4. Docker 이미지 빌드
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/roomfit-server:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/roomfit-server:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/roomfit-server:latest

      # 5. Docker 이미지 Push
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/roomfit-server:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/roomfit-server:latest
